### ISSUE TITLE
Prefix lines with plugin name

### ISSUE THREAD

**Issue by localjo** [nebez/gulp-semistandard#4]
We're using this in a gulp task that runs at the same time as some linters for other files, so both are logging to the console at the same time. This causes a bit of confusion about which errors are coming from which reporter. It would be nice if the log lines could be prefixed with the plugin name so it's clear where they're coming from. I'm happy to open a PR, if you think this would be a useful feature.

**Comment by nebez** [comment]
@josiahsprague sounds like a good idea to me. I'd definitely be open to a PR.

**Comment by localjo** [comment]
Cool. I've got a working one ready, I'll open the PR soon after a little more review.
